apiVersion: v1
kind: Service
metadata:
  name: elliot-api-service
  labels:
    app: elliot-api
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: elliot-api
