apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: service.patch.yaml

secretGenerator:
  - behavior: replace
    envs:
      - secrets.env
    name: elliot-api-secret
    type: Opaque
