name: Elliot for the win
on: [ push ]
env:
  APP_VERSION: 0.0.1
  IMAGE_NAME: ventilo/elliot-api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: |
          GOOS=linux GOARCH=amd64 go build -o .build/app
      - uses: actions/upload-artifact@v3
        with:
          name: app
          path: .build/app

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: set_img
      run: echo "::set-output name=image::${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}-$(git rev-parse --short HEAD)"
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/download-artifact@v3
      with:
        name: app
        path: .build/app
    - uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: ${{ steps.set_img.outputs.image }}
