name: Elliot for the win
on: [ push ]
env:
  APP_VERSION: 0.0.1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: |
          GOOS=linux GOARCH=amd64 go build -o .build/app
      - uses: actions/upload-artifact@v3
        with:
          name: app
          path: .build/app

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/download-artifact@v3
      with:
        name: app
        path: .build/app
    - run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ventilo/elliot-api:${{ env.APP_VERSION }}-${{ steps.vars.outputs.sha_short }}
